version: '3.9'

services:
  employees.service.postgres:
    image: postgres:15.3
    container_name: employees.service.postgres
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - ./config/.postgres.env
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

  employees.service.app:
    container_name: employees.service.app
    build:
      context: ../../
      dockerfile: ./apps/employess.service/Dockerfile
    depends_on:
      - employees.service.postgres
    volumes:
      - ./volumes/logs:/app/logs
    ports:
      - '3001:3000'
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  postgres-data:
    driver: local
