version: '3.9'

services:
  database:
    image: postgres:15.3
    container_name: database
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:7.4
    container_name: cache
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 12345
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./volumes/redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

