version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    env_file:
      - ./config/.elastic.env
    ports:
      - '9200:9200'
    volumes:
      - ./volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - shared-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ./config/.kibana.env
    depends_on:
      - elasticsearch
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  elasticsearch-data:
    driver: local
